State Machine for IMU Gestures
ECE-180D-WS-2022/Team3 pull request #150
Opened 2022-04-23 04:04 UTC by asrendon24

- Declared three gestures to be recognized for our game: upward/downward movement, and forward push for shooting
- Line 504 is the beginning of the state machine
- Lines 504 - 521 checks if IMU points upwards, and if it detects a "flick", then sends a message through MQTT to move upwards via IMU_dict dictionary
- Lines 523 - 541 checks if IMU is pointing down, and then also if there is a "flick", also sends a message
- Lines 542 - 553 check if the IMU is pointing straight, and if there is a forward push for the shooting gesture

2022-04-23 04:41 UTC, asrendon24 commented
updated ImuIface.py to include new boolean values for upward/downward movement, and shooting. Also deleted tilt recognition code

2022-04-25 21:12 UTC, randallwc commented on client/ImuIface.py
> +            self.is_shooting = self.IMU_dict['is_shooting']
what is the diff between `is_pushing` and `is_shooting`?

2022-04-25 21:15 UTC, randallwc requested changes

2022-04-25 21:15 UTC, randallwc commented on client/ImuIface.py
>          self.y_gyro = 0.0
the ones that are not being updated should be removed because this will be confusing in the long run if someone tries to check the ones that are dead links

2022-04-25 21:15 UTC, randallwc commented on client/ImuIface.py
> +            #self.is_left_tilt = 5 < self.IMU_dict["y_gyro"] < 80
delete

2022-04-25 21:15 UTC, randallwc commented on client/ImuIface.py
> +            #self.is_pushing = self.IMU_dict['is_pushing']
delete

2022-04-25 21:16 UTC, randallwc commented on client/ImuIface.py
> +            #self.previous_time = self.new_time
delete

2022-04-26 03:59 UTC, merged