Simple multiplayer, just moving player on other person's screen
ECE-180D-WS-2022/Team3 pull request #6
Opened 2022-02-23 00:29 UTC by jcr7467

Added multiplayer file, split up classes into a new file and imported them. added socket functionality so that the client can see their opponents position. Added functions to server to simplify emitting inside of socket connection

2022-02-23 00:30 UTC, jcr7467 commented
@all, just look through it to at least be somewhat familiar with it @asrendon24 couldn't add you as reviewer, take a look

2022-02-23 02:54 UTC, antonalcala approved these changes
yupp let's go

2022-02-24 10:49 UTC, randallwc requested changes
- needs to support multiple connections before the merge
- needs to have 3 files (main loop, single-player, multiplayer)

2022-02-24 10:49 UTC, randallwc commented on server/server.js
> +};
need to add functionality for multiple players in one room

2022-02-24 10:49 UTC, randallwc commented on server/server.js
> +            socket.broadcast.to(roomID).emit('opponentLasered')
multiple players

2022-02-24 10:49 UTC, randallwc commented on server/server.js
> +            message: "New member has joined!"
broadcast unique id

2022-02-24 10:49 UTC, randallwc commented on main_multiplayer.py
> +    pygame.display.update()
main loop should be in it's own file

2022-02-24 10:49 UTC, randallwc commented on main_multiplayer.py
> +    OpponentRanger.UpdateCoords(data['xCoord'], data['yCoord'])
should be in it's own file separate from main loop

2022-02-24 10:49 UTC, randallwc commented on common/gameobjects.py
> +'''
should be in main file

2022-03-02 07:08 UTC, closed without merging